function ddq_n = compute_ddq(in1)
%COMPUTE_DDQ
%    DDQ_N = COMPUTE_DDQ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Feb-2020 18:30:40

%Version: 1.1
dphiL = in1(4,:);
dphiR = in1(5,:);
dtheta = in1(6,:);
tauL = in1(7,:);
tauR = in1(8,:);
theta = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
t7 = -tauL;
t8 = -tauR;
t9 = dphiL./5.0e+1;
t10 = dphiR./5.0e+1;
t11 = dtheta./5.0e+1;
t12 = dphiL.*(1.1e+1./5.0e+1);
t13 = dphiR.*(1.1e+1./5.0e+1);
t5 = t2.^2;
t6 = t3.^2;
t14 = -t11;
t15 = -t12;
t16 = -t13;
t17 = t3.*t4.*(3.0./2.5e+1);
t19 = t3.*2.3544e+1;
t18 = t5.*(6.0./1.25e+2);
t20 = t5.*(6.0./6.25e+2);
t21 = t5.*9.6e-4;
t22 = t6.*(1.8e+1./1.25e+2);
t23 = t5.*(5.4e+1./6.25e+2);
t24 = t6.*(4.2e+1./6.25e+2);
t25 = t6.*(6.6e+1./6.25e+2);
t26 = t6.*2.112e-3;
t27 = t11+t15+t17+tauL;
t28 = t11+t16+t17+tauR;
t35 = t7+t8+t9+t10+t14+t19;
t29 = t22+t23+5.1e+1./2.5e+2;
t30 = t18+t25+1.496e-1;
t31 = t20+t24+9.52e-2;
t32 = t21+t26+2.992e-3;
t33 = 1.0./t30;
t34 = 1.0./t32;
t36 = t2.*t33.*t35.*(6.0./2.5e+1);
t37 = -t36;
ddq_n = [t37+(t27.*t29.*t34)./2.0-(t28.*t31.*t34)./2.0;t37+(t28.*t29.*t34)./2.0-(t27.*t31.*t34)./2.0;t33.*t35.*(1.1e+1./1.0e+2)-t2.*t27.*t33.*(6.0./2.5e+1)-t2.*t28.*t33.*(6.0./2.5e+1)];
