function ddq = compute_ddq(in1)
%COMPUTE_DDQ
%    DDQ = COMPUTE_DDQ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    06-Feb-2020 14:46:20

%Version: 1.1
dtheta = in1(6,:);
tauL = in1(7,:);
tauR = in1(8,:);
theta = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
t5 = t2.^2;
t6 = t3.^2;
t13 = (t3.*t4)./5.0;
t14 = t3.*(9.81e+2./2.5e+1);
t7 = t5.*1.0e+1;
t8 = t5.*1.1e+2;
t9 = t5.*2.1e+2;
t10 = t6.*9.0e+1;
t11 = t6.*1.9e+2;
t12 = t6.*2.9e+2;
t15 = -t14;
t16 = t13+tauL;
t17 = t13+tauR;
t18 = t15+tauL+tauR;
t19 = t7+t10+1.17e+2;
t20 = t8+t11+2.47e+2;
t21 = t9+t12+3.77e+2;
t22 = 1.0./t20;
t23 = t2.*t18.*t22.*2.0e+2;
ddq = [t23-t17.*t19.*t22.*1.0e+1+t16.*t21.*t22.*1.0e+1;t23-t16.*t19.*t22.*1.0e+1+t17.*t21.*t22.*1.0e+1;t18.*t22.*-9.5e+1-t2.*t16.*t22.*2.0e+2-t2.*t17.*t22.*2.0e+2];
