function A_con = compute_A(R,L,mw,mb,Iw,Ib,By,Bm)
%COMPUTE_A
%    A_CON = COMPUTE_A(R,L,MW,MB,IW,IB,BY,BM)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Feb-2020 18:30:40

%Version: 1.0
t2 = Ib.*2.0;
t3 = Iw.*2.0;
t4 = L.^2;
t5 = R.^2;
t6 = mb.^2;
t7 = L.*R.*mb;
t8 = 1.0./Iw;
t14 = Bm.*Ib.*R.*mb;
t15 = By.*Ib.*R.*mb;
t28 = Bm.*Iw.*L.*mb.*-2.0;
t9 = Bm.*t3;
t10 = Iw.*t2;
t13 = mb.*t5;
t16 = Bm.*t7;
t17 = By.*t7;
t18 = mb.*t4.*4.0;
t19 = mw.*t5.*2.0;
t21 = Bm.*R.*mw.*t2;
t22 = By.*R.*mw.*t2;
t26 = Bm.*Ib.*mw.*t5;
t27 = By.*Ib.*mw.*t5;
t31 = mw.*t2.*t5;
t34 = Bm.*R.*t4.*t6;
t35 = By.*R.*t4.*t6;
t40 = t4.*t5.*t6;
t11 = Bm.*t10;
t12 = By.*t10;
t20 = L.*mb.*t9;
t23 = Bm.*t13;
t24 = Ib.*t13;
t25 = Iw.*t16;
t29 = Bm.*t19;
t30 = Iw.*t18;
t36 = Bm.*R.*mw.*t18;
t37 = By.*R.*mw.*t18;
t41 = mw.*t4.*t13.*4.0;
t43 = By.*mw.*t4.*t13.*2.0;
t44 = (Bm.*t40)./2.0;
t45 = (By.*t40)./2.0;
t46 = t2+t7+t18;
t32 = Bm.*t30;
t33 = By.*t30;
t38 = (Ib.*t23)./2.0;
t39 = (By.*t24)./2.0;
t42 = mw.*t4.*t23.*2.0;
t47 = t9+t16+t17+t23+t29;
t48 = t10+t24+t30+t31+t40+t41;
t53 = t14+t15+t21+t22+t28+t34+t35+t36+t37;
t49 = 1.0./t48;
t55 = t11+t12+t25+t26+t27+t32+t33+t38+t39+t42+t43+t44+t45;
t50 = R.*t4.*t6.*t49.*(9.81e+2./1.0e+2);
t51 = Bm.*t46.*t49;
t54 = t47.*t49;
t56 = (R.*t8.*t49.*t53)./2.0;
t57 = t8.*t49.*t55;
t52 = -t50;
t58 = -t57;
A_con = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t52,t52,L.*mb.*t49.*(t3+t13+t19).*(9.81e+2./1.0e+2),1.0,0.0,0.0,t58,t56,t54,0.0,1.0,0.0,t56,t58,t54,0.0,0.0,1.0,t51,t51,-Bm.*t49.*(t3+t7.*2.0+t13+t19)],[6,6]);
