function B_con = compute_B(R,L,mw,mb,Iw,Ib,By,Bm)
%COMPUTE_B
%    B_CON = COMPUTE_B(R,L,MW,MB,IW,IB,BY,BM)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Feb-2020 18:30:41

%Version: 1.0
t2 = Iw.*2.0;
t3 = L.^2;
t4 = R.^2;
t5 = mb.^2;
t6 = Ib.*R.*mb;
t7 = L.*R.*mb;
t8 = 1.0./Iw;
t11 = Ib.*R.*mw.*2.0;
t14 = Iw.*L.*mb.*-2.0;
t9 = Ib.*t2;
t10 = L.*mb.*t2;
t12 = mb.*t4;
t13 = Iw.*t7;
t15 = mw.*t4.*2.0;
t17 = Ib.*mw.*t4;
t18 = Iw.*mb.*t3.*4.0;
t20 = R.*t3.*t5;
t21 = R.*mb.*mw.*t3.*4.0;
t23 = t3.*t4.*t5;
t16 = Ib.*t12;
t19 = Ib.*t15;
t24 = mw.*t3.*t12.*2.0;
t25 = mw.*t3.*t12.*4.0;
t26 = t23./2.0;
t27 = t2+t7+t12+t15;
t28 = t6+t11+t14+t20+t21;
t22 = t16./2.0;
t29 = t9+t16+t18+t19+t23+t25;
t30 = 1.0./t29;
t31 = t9+t13+t17+t18+t22+t24+t26;
t32 = t27.*t30;
t34 = (R.*t8.*t28.*t30)./2.0;
t36 = t8.*t30.*t31;
t33 = -t32;
t35 = -t34;
B_con = reshape([0.0,0.0,0.0,t36,t35,t33,0.0,0.0,0.0,t35,t36,t33],[6,2]);
