function N = compute_N(g,l,mb,theta)
%COMPUTE_N
%    N = COMPUTE_N(G,L,MB,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Dec-2019 18:18:07

%Version: 1.1
N = [-g.*l.*mb.*sin(theta);0.0;0.0];
