function N = compute_N(g,l,mb,theta)
%COMPUTE_N
%    N = COMPUTE_N(G,L,MB,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Nov-2019 13:41:36

%Version: 1.1
N = [-g.*l.*mb.*sin(theta);0.0;0.0];
