function C_bar = compute_C_bar(dtheta,l,mb,r,theta)
%COMPUTE_C_BAR
%    C_BAR = COMPUTE_C_BAR(DTHETA,L,MB,R,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Dec-2019 18:18:07

%Version: 1.1
t2 = sin(theta);
t3 = (dtheta.*l.*mb.*r.*t2)./2.0;
t4 = -t3;
C_bar = reshape([0.0,t4,t4,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
